apiVersion: batch/v1
kind: Job
metadata:
  name: integration-test-1751719756
spec:
  template:
    spec:
      containers:
      - name: integration-test
        image: gcsfileproxy-tests
        imagePullPolicy: Never
        env:
        - name: STORAGE_EMULATOR_HOST
          value: "gcs-emulator:4443"
        - name: VERIFICATION_SERVICE_URL
          value: "http://verification-service:8080/verify"
        - name: PROXY_HOST
          value: "http://gcsfileproxy:80"
        - name: GOOGLE_CLOUD_PROJECT
          value: "test-project"
        command: ["npm", "test"]
      restartPolicy: Never
  backoffLimit: 1
