apiVersion: v1
kind: PersistentVolume
metadata:
  name: gcs-emulator-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/gcs-emulator
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcs-emulator-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
