apiVersion: batch/v1
kind: Job
metadata:
  name: integration-tests
spec:
  template:
    spec:
      containers:
      - name: integration-tests
        image: gcsfileproxy-tests
        env:
        - name: GCS_EMULATOR_ENDPOINT
          value: "http://gcs-emulator:4443"
        - name: VERIFICATION_SERVICE_URL
          value: "http://verification-service:8080/verify"
        - name: PROXY_HOST
          value: "http://gcsfileproxy:80"
        - name: GOOGLE_CLOUD_PROJECT
          value: "test-project"
      restartPolicy: Never
  backoffLimit: 4
